version: "3.9"

services:
 backend:
  build: .
  container_name: django
  command: gunicorn config.wsgi --bind 0.0.0.0:8000
  volumes:
   - .:/core
   - static_volume:/core/static
   - media_volume:/core/media

  expose:
   - "8000"
  depends_on:
   - redis

 redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

 worker1:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/core
    depends_on:
      - redis
      - backend

 nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/core/static
      - media_volume:/home/core/media

    depends_on:
      - redis
      - backend

volumes:
  static_volume:
  media_volume:



